apps/df_goods/urls.py
from django.conf.urls import url

from . import views

app_name = 'df_goods'

urlpatterns = [
    url('^$', views.index, name="index"),
    url('^list(\d+)_(\d+)_(\d+)/$', views.good_list, name="good_list"),
    url('^(\d+)/$', views.detail, name="detail"),
    url(r'^search/', views.ordinary_search, name="ordinary_search"),  # 全文检索
]

apps/df_user/urls.py
#!/user/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import *

app_name = 'df_user'

urlpatterns = [
    url(r'^register/$', register, name="register"),
    url(r'^register_handle/$', register_handle, name="register_handle"),
    url(r'^register_exist/$', register_exist, name="register_exist"),
    url(r'^login/$', login, name="login"),
    url(r'^login_handle/$', login_handle, name="login_handle"),
    url(r'^info/$', info, name="info"),
    url(r'^order/(\d+)$', order, name="order"),
    url(r'^site/$', site, name="site"),
    # url(r'^place_order/$', views.place_order),
    url(r'^logout/$', logout, name="logout"),
    url(r'^password/$', password, name="password"),  # 渲染页面
    url(r'^password_exist/$', password_exist, name="password_exist"),  # 验证用户名是否存在
    url(r'^password_1/$', password_1, name="password_1"),  # 对用户名和邮箱进行验证
    url(r'^password_again/$', password_again, name="password_again"),  # 用户修改密码
    url(r'^password_jiu/$', password_jiu, name="password_jiu"),  # 验证旧密码

]

apps/user_action/urls.py
#!/user/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import *

app_name = 'user_action'

urlpatterns = [
    url(r'^add_comment/$', add_comment, name="add_comment"),
    # url(r'^register_handle/$', register_handle, name="register_handle"),
    # url(r'^register_exist/$', register_exist, name="register_exist"),
    # url(r'^login/$', login, name="login"),
    # url(r'^login_handle/$', login_handle, name="login_handle"),
    # url(r'^info/$', info, name="info"),
    # url(r'^order/(\d+)$', order, name="order"),
    # url(r'^site/$', site, name="site"),
    # url(r'^logout/$', logout, name="logout"),
]

daily_fresh_demo/urls.py
from django.contrib import admin
<<<<<<< HEAD
from django.urls import path
=======
import xadmin
from django.urls import path,re_path
>>>>>>> 179e61dbddb0904127c8715edb6e9a1cf02e0095
from django.conf.urls import url, include
from django.views.static import serve  # 上传文件处理函数
from df_user.views import ForgetPwdView,ResetView,ModifyPwdView
from .settings import MEDIA_ROOT,STATIC_ROOT

<<<<<<< HEAD
import xadmin
from .settings import MEDIA_ROOT
=======
>>>>>>> 179e61dbddb0904127c8715edb6e9a1cf02e0095



urlpatterns = [
<<<<<<< HEAD
    path('admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),
=======
    # path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),

>>>>>>> 179e61dbddb0904127c8715edb6e9a1cf02e0095
    url(r'^', include('df_goods.urls', namespace='df_goods')),
    url(r'^user/', include('df_user.urls', namespace='df_user')),
    url(r'^cart/', include('df_cart.urls', namespace='df_cart')),
    url(r'^order/', include('df_order.urls', namespace='df_order')),
    url(r'^user_action/', include('user_action.urls', namespace='user_action')),
    url(r'^tinymce/', include('tinymce.urls')),  # 使用富文本编辑框配置confurl
    url(r'^media/(?P<path>.*)$', serve, {"document_root":MEDIA_ROOT}),
    # 关闭debug模式
    re_path('static/(?P<path>.*)', serve, {'document_root': STATIC_ROOT}),


    # 忘记密码修改
    path('forget/', ForgetPwdView.as_view(), name='forget_pwd'),
    re_path('reset/(?P<active_code>.*)/', ResetView.as_view(), name='reset_pwd'),
    path('modify_pwd/', ModifyPwdView.as_view(), name='modify_pwd'),
]

apps/df_order/models.py
from django.db import models

from df_goods.models import GoodsInfo
from df_user.models import UserInfo

class OrderInfo(models.Model):  # 大订单
    oid = models.CharField(max_length=20, primary_key=True, verbose_name="大订单号")
    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE, verbose_name="订单用户")
    odate = models.DateTimeField(auto_now=True, verbose_name="时间")
    oIsPay = models.BooleanField(default=False, verbose_name="是否支付")
    ototal = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="总价")
    oaddress = models.CharField(max_length=150, verbose_name="收货地址")
    # 虽然订单总价可以由多个商品的单价以及数量求得，但是由于用户订单的总价的大量使用，忽略total的冗余度

    class Meta:
        verbose_name = "订单"
        verbose_name_plural = verbose_name

    def __str__(self):
        # return self.user.uname + "在" + str(self.odate) + "的订单"
        return "{0}在的订单{1}".format(self.user.uname, self.odate)


# 无法实现：真实支付，物流信息
class OrderDetailInfo(models.Model):  # 大订单中的具体某一商品订单

    goods = models.ForeignKey(GoodsInfo, on_delete=models.CASCADE, verbose_name="商品")  # 关联商品信息
    order = models.ForeignKey(OrderInfo, on_delete=models.CASCADE, verbose_name="订单")
    price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="商品价格")
    count = models.IntegerField(verbose_name="商品数")

    class Meta:
        verbose_name = "订单详情"
        verbose_name_plural = verbose_name

    def __str__(self):
        # return self.goods.gtitle + "(数量为" + str(self.count)  + ")"
        return "{0}(数量为{1})".format(self.goods.gtitle, self.count)

apps/df_user/models.py
from django.db import models

from datetime import datetime

from df_goods.models import GoodsInfo


class UserInfo(models.Model):

    uname = models.CharField(max_length=20, verbose_name="用户名", unique=True)
    upwd = models.CharField(max_length=40, verbose_name="用户密码", blank=False)
    uemail = models.EmailField(verbose_name="邮箱", unique=True)
    ushou = models.CharField(max_length=20, default="", verbose_name="收货地址")
    uaddress = models.CharField(max_length=100, default="", verbose_name="地址")
    uyoubian = models.CharField(max_length=6, default="", verbose_name="邮编")
    uphone = models.CharField(max_length=11, default="", verbose_name="手机号")
    # default,blank是python层面的约束，不影响数据库表结构，修改时不需要迁移 python manage.py makemigrations

    class Meta:
        verbose_name = "用户信息"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.uname


class GoodsBrowser(models.Model):

    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE, verbose_name="用户ID")
    good = models.ForeignKey(GoodsInfo, on_delete=models.CASCADE, verbose_name="商品ID")
    browser_time = models.DateTimeField(default=datetime.now, verbose_name="浏览时间")

    class Meta:
        verbose_name = "用户浏览记录"
        verbose_name_plural = verbose_name

    def __str__(self):
        return "{0}浏览记录{1}".format(self.user.uname, self.good.gtitle)


class EmailVerifyRecord(models.Model):
    code = models.CharField(max_length=20, verbose_name=u"验证码")
    email = models.EmailField(max_length=50, verbose_name=u'邮箱')
    send_type = models.CharField(choices=(('register', '注册'), ('forget', u'找回密码'), ('change', '更改邮箱')),
                                 max_length=20, verbose_name=u'验证码类型')
    send_time = models.DateTimeField(default=datetime.now, verbose_name=u'发送时间')

    class Meta:
        verbose_name = u"邮箱验证码"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.code

apps/df_user/forms.py
from django import forms

class ForgetForm(forms.Form):
    email = forms.EmailField(required=True)

class ModifyForm(forms.Form):
    password1 = forms.CharField(required=True, min_length=5)
    password2 = forms.CharField(required=True, min_length=5)

apps/df_user/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, reverse
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.views.generic.base import View
from django.contrib.auth.hashers import make_password

from hashlib import sha1

from .models import GoodsBrowser,EmailVerifyRecord
from . import user_decorator
from .forms import ForgetForm,ModifyForm
from df_order.models import *

from utils.email_send import send_register_email


def register(request):

    context = {
        'title': '用户注册',
    }
    return render(request, 'df_user/register.html', context)


def register_handle(request):
    username = request.POST.get('user_name')
    password = request.POST.get('pwd')
    confirm_pwd = request.POST.get('confirm_pwd')
    email = request.POST.get('email')

    # 判断两次密码一致性
    if password != confirm_pwd:
        return redirect('/user/register/')
    # 密码加密
    s1 = sha1()
    s1.update(password.encode('utf8'))
    encrypted_pwd = s1.hexdigest()

    # 创建对象
    UserInfo.objects.create(uname=username, upwd=encrypted_pwd, uemail=email)
    # 注册成功
    context = {
        'title': '用户登陆',
        'username': username,
    }
    return render(request, 'df_user/login.html', context)

def forget_pwd(request):
    if request.method=='POST':
        username = request.POST.get('user_name')
        password = request.POST.get('pwd')
        confirm_pwd = request.POST.get('confirm_pwd')
        email = request.POST.get('email')





def register_exist(request):
    username = request.GET.get('uname')
    count = UserInfo.objects.filter(uname=username).count()
    return JsonResponse({'count': count})


def login(request):
    uname = request.COOKIES.get('uname', '')
    context = {
        'title': '用户登陆',
        'error_name': 0,
        'error_pwd': 0,
        'uname': uname,
    }
    return render(request, 'df_user/login.html', context)


class ForgetPwdView(View):
    def get(self, request):
        forget_form = ForgetForm(request.GET)
        return render(request, 'df_user/forgetpwd.html', {'forget_form': forget_form})

    def post(self, request):
        forget_form = ForgetForm(request.POST)
        if forget_form.is_valid():
            email = request.POST.get('email', '')
            send_register_email(email, 'forget')
            return render(request, 'df_user/forgetpwd.html', {'forget_form': forget_form, 'msg': '重置密码连接已发送，请注意查收！'})
        else:
            return render(request, 'df_user/forgetpwd.html', {'forget_form': forget_form})
class ResetView(View):
    def get(self, request, active_code):
        all_record = EmailVerifyRecord.objects.filter(code=active_code)
        if all_record:
            for record in all_record:
                email = record.email
                return render(request, 'df_user/password_reset.html', {'email': email})
        else:
            return render(request, 'df_user/forgetpwd.html', {'msg': '重置密码连接无效，请重新请求'})


class ModifyPwdView(View):
    def post(self, request):
        modify_form = ModifyForm(request.POST)
        if modify_form.is_valid():
            pwd1 = request.POST.get('password1', '')
            pwd2 = request.POST.get('password2', '')
            email = request.POST.get('email', '')
            if pwd1 != pwd2:
                return render(request, 'df_user/password_reset.html', {'email': email, 'modify_form': modify_form, 'msg': '两次密码不同，请修改！'})
            else:
                user = UserInfo.objects.get(uemail=email)
                # 密码加密
                s1 = sha1()
                s1.update(pwd2.encode('utf8'))
                encrypted_pwd = s1.hexdigest()

                user.upwd = encrypted_pwd
                user.save()
                return render(request, 'df_user/login.html', {'msg': '密码修改成功，请登录'})
        else:
            email = request.POST.get('email', '')
            return render(request, 'df_user/password_reset.html', {'email': email, 'modify_form': modify_form})


def login_handle(request):  # 没有利用ajax提交表单
    # 接受请求信息
    uname = request.POST.get('username')
    upwd = request.POST.get('pwd')
    jizhu = request.POST.get('jizhu', 0)
    users = UserInfo.objects.filter(uname=uname)
    if len(users) == 1:  # 判断用户密码并跳转
        s1 = sha1()
        s1.update(upwd.encode('utf8'))
        if s1.hexdigest() == users[0].upwd:
            url = request.COOKIES.get('url', '/')
            red = HttpResponseRedirect(url)  # 继承与HttpResponse 在跳转的同时 设置一个cookie值
            # 是否勾选记住用户名，设置cookie
            if jizhu != 0:
                red.set_cookie('uname', uname)
            else:
                red.set_cookie('uname', '', max_age=-1)  # 设置过期cookie时间，立刻过期
            request.session['user_id'] = users[0].id
            request.session['user_name'] = uname
            return red
        else:
            context = {
                'title': '用户名登陆',
                'error_name': 0,
                'error_pwd': 1,
                'uname': uname,
                'upwd': upwd,
            }
            return render(request, 'df_user/login.html', context)
    else:
        context = {
            'title': '用户名登陆',
            'error_name': 1,
            'error_pwd': 0,
            'uname': uname,
            'upwd': upwd,
        }
        return render(request, 'df_user/login.html', context)


def logout(request):  # 用户登出
    request.session.flush()  # 清空当前用户所有session
    return redirect(reverse("df_goods:index"))


@user_decorator.login
def info(request):  # 用户中心
    username = request.session.get('user_name')
    user = UserInfo.objects.filter(uname=username).first()
    browser_goods = GoodsBrowser.objects.filter(user=user).order_by("-browser_time")
    goods_list = []
    if browser_goods:
        goods_list = [browser_good.good for browser_good in browser_goods]  # 从浏览商品记录中取出浏览商品
        explain = '最近浏览'
    else:
        explain = '无最近浏览'

    context = {
        'title': '用户中心',
        'page_name': 1,
        'user_phone': user.uphone,
        'user_address': user.uaddress,
        'user_name': username,
        'goods_list': goods_list,
        'explain': explain,
    }
    return render(request, 'df_user/user_center_info.html', context)


@user_decorator.login
def order(request, index):
    user_id = request.session['user_id']
    orders_list = OrderInfo.objects.filter(user_id=int(user_id)).order_by('-odate')
    paginator = Paginator(orders_list, 2)
    page = paginator.page(int(index))
    context = {
        'paginator': paginator,
        'page': page,
        # 'orders_list':orders_list,
        'title': "用户中心",
        'page_name': 1,
    }
    return render(request, 'df_user/user_center_order.html', context)


@user_decorator.login
def site(request):
    user = UserInfo.objects.get(id=request.session['user_id'])
    if request.method == "POST":
        user.ushou = request.POST.get('ushou')
        user.uaddress = request.POST.get('uaddress')
        user.uyoubian = request.POST.get('uyoubian')
        user.uphone = request.POST.get('uphone')
        user.save()
    context = {
        'page_name': 1,
        'title': '用户中心',
        'user': user,
    }
    return render(request, 'df_user/user_center_site.html', context)

def password(request):
    """
    找回密码页面
    :param request:
    :return:
    """
    return render(request, 'df_user/password.html')

def password_exist(request):
    username = request.GET.get('uname')
    count = UserInfo.objects.filter(uname=username).count()
    return JsonResponse({'count': count})


def password_1(request):
    """
    验证用户名和密码
    :param request:
    :return:
    """
    username = request.GET.get("user_name")
    email = request.GET.get("email")
    password = request.GET.get("password")
    user = UserInfo.objects.filter(uname=username)
    if user:
        user = user[0]
    con = {
        'title': '用户登陆',
        'username': username,
    }
    if str(user.uemail) == str(email):
        count = 1
        s1 = sha1()
        s1.update(password.encode('utf8'))
        encrypted_pwd = s1.hexdigest()
        user.upwd = encrypted_pwd
        user.save()
    else:
        count = 0
    return JsonResponse({'count': count})


@user_decorator.login
def password_again(request):
    """
    修改用户密码
    :param request:
    :return:
    """
    user_id = request.session['user_id']
    user = UserInfo.objects.filter(id=user_id)
    user = user[0]
    if request.method == "POST":
        user.ushou = request.POST.get('ushou')
        user.uaddress = request.POST.get('uaddress')
        user.uyoubian = request.POST.get('uyoubian')
        user.uphone = request.POST.get('uphone')
        user.save()
    context = {
        'page_name': 1,
        'title': '修改密码',
        'user': user,
    }
    return render(request,'df_user/user_password_reg.html',context)


def password_jiu(request):
    """
    验证用户的旧密码
    :param request:
    :return:
    """
    user_id = request.session['user_id']
    user = UserInfo.objects.filter(id=user_id)
    user = user[0]
    password1 = request.GET.get("password1")
    password2 = request.GET.get("password2")
    password3 = request.GET.get("password3")
    s1 = sha1()
    s1.update(password1.encode('utf8'))
    encrypted_pwd1 = s1.hexdigest()
    s1 = sha1()
    s1.update(password2.encode('utf8'))
    encrypted_pwd2 = s1.hexdigest()
    if user.upwd == encrypted_pwd1:
        user.upwd=encrypted_pwd2
        user.save()
        data = 1
    else:
        data = 0
    return JsonResponse({'count': data})

templates/df_user/user_center_order.html
{% extends 'base.html' %}
{% block center_body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url "df_user:info" %}">· 个人信息</a></li>
				<li><a href="{% url "df_user:order" 1 %}" class="active">· 全部订单</a></li>
				<li><a href="{% url "df_user:site" %}">· 收货地址</a></li>
                <li><a href="{% url "df_user:password_again" %}">· 修改密码</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
                {% for orderinfo in page %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ orderinfo.odate|date }}</li>
					<li class="col02">订单号：{{ orderinfo.oid }}</li>
					<li class="col02 stress">已支付</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for order_detail in orderinfo.orderdetailinfo_set.all %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="{{ MEDIA_URL }}{{ order_detail.goods.gpic }}"></li>
                                    <li class="col02">{{ order_detail.goods.gtitle }}<em class="good_price">{{ order_detail.goods.gprice }}</em>元/<em>{{ order_detail.goods.gunit }}</em></li>
									<li class="col03">{{ order_detail.count }}件</li>
									<li class="col04">11.80元</li>
                                    <li class="col05" style="display: none;">{{ order_detail.goods.id }}</li>
								</ul>
                                {% endfor %}
							</td>
							<td width="10%">{{ orderinfo.ototal }}元</td>
							<td width="10%">已付款</td>
							<td width="10%"><a href="#" class="oper_btn">查看物流</a></td>
                            <td width="10%"><a class="comment_btn">评价</a></td>
						</tr>
					</tbody>
				</table>
			    {% endfor %}


				<div class="pagenation">
                    {% if page.has_previous %}
					    <a href="{% url "df_user:order" page.previous_page_number %}">上一页</a>
                    {% endif %}

                    {% for index in paginator.page_range %}
                        {% if index == page.number %}
                            <a href="{% url "df_user:order" index %}" class="active">{{ index }}</a>
                        {% else %}
                            <a href="{% url "df_user:order" index %}">{{ index }}</a>
                        {% endif %}
                    {% endfor %}

                    {% if page.has_next %}
					    <a href="{% url "df_user:order" page.next_page_number %}">下一页></a>
                    {% endif %}
				</div>
		</div>
	</div>

    {#    弹出层#}
    <div id="popover" hidden>
        <textarea name="" id="" cols="30" rows="10" placeholder="请在此处输入您的评价" style="border: 0;width: 100%;height: 100%"></textarea>
    </div>
    <script src="../../static/js/layer.js"></script>
    <script type="text/javascript">
    $(function () {
        $('.col04').each(function () {
            count = $(this).prev().text();
            price = $(this).prev().prev().find('.good_price').text();
            $(this).html(parseFloat(count,2)*parseFloat(price,2)+'元');
            }

        )
        }
    )
    
    $(".comment_btn").click(function () {
        var _this = this
        var mylayer = layer.open({
            type: 1,
            title: "填写商品评论",
            closeBtn: 0,
            shadeClose: true,
            skin: 'mypopover',
            content: $('#popover'),
            btn:["确定","取消"],
            yes: function(index, layero){
                var txtvalue = $("#popover>textarea").val();
                if(txtvalue == ''){
                    layer.msg("评论不能为空");
                }else {
                    console.log(txtvalue);
                    submit_comment(_this,txtvalue);
                    layer.close(mylayer)
                }
             }
            });
    })
    function submit_comment(dom,comment_value){
        var goods_id = $(dom).parent().siblings().find('li.col05').text();
        console.log(goods_id);
        var data = {
            goods_id:goods_id,
            comment: comment_value,
            'csrfmiddlewaretoken':'{{ csrf_token }}'
        };
        $.ajax({
                    type:"POST",
                    data: data,
                    url: "{% url 'user_action:add_comment'%}",
                    cache: false,
                    dataType: "json",
                    success: function(result, statues, xml) {
                        layer.msg(result.msg)
                    },
                    error: function(result){
                        layer.msg(result.msg)
                    }
                });
    }

    </script>

{% endblock center_body %}

templates/df_user/user_center_site.html
{% extends 'base.html' %}

{% block center_body %}


	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
                <li><a href="{% url "df_user:info" %}">· 个人信息</a></li>
				<li><a href="{% url "df_user:order" 1 %}">· 全部订单</a></li>
				<li><a href="{% url "df_user:site" %}" class="active">· 收货地址</a></li>
                <li><a href="{% url "df_user:password_again" %}">· 修改密码</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
                        <dt>收件人：{{ user.ushou }}</dt>
                        <dt>电话：{{ user.uphone }}</dt>
                        <dt>当前地址：{{ user.uaddress }}</dt>
{#                        <a href="/user/place_order" style="display: block; width: 80px; height:30px; line-height: 30px; text-align: center;font-size: 13px; " class="info_submit">提交订单</a>#}
					</dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="{% url "df_user:site" %}" method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="ushou" value="{{ user.ushou }}">
						</div>
                        <div class="form_group">
                            <label>手机：</label>
                            <input type="text" name="uphone" value="{{ user.uphone }}">
                        </div>
                        <div class="form_group">
                            <label>邮编：</label>
                            <input type="text" name="uyoubian" value="{{ user.uyoubian }}">
                        </div>
                        <div class="form_group form_group2">
                            <label>详细地址：</label>
                            <textarea class="site_area" name="uaddress" >{{ user.uaddress }}</textarea>
                        </div>
						<input type="submit" name="" value="修改地址" class="info_submit">
					</form>
				</div>
		</div>
	</div>


{% endblock center_body %}

templates/df_user/user_password_reg.html
{% extends 'base.html' %}

{% block center_body %}


	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
                <li><a href="{% url "df_user:info" %}">· 个人信息</a></li>
				<li><a href="{% url "df_user:order" 1 %}">· 全部订单</a></li>
				<li><a href="{% url "df_user:site" %}">· 收货地址</a></li>
                <li><a href="{% url "df_user:password_again" %}" class="active">· 修改密码</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
                        <dt>收件人：{{ user.ushou }}</dt>
                        <dt>电话：{{ user.uphone }}</dt>
                        <dt>当前地址：{{ user.uaddress }}</dt>
{#                        <a href="/user/place_order" style="display: block; width: 80px; height:30px; line-height: 30px; text-align: center;font-size: 13px; " class="info_submit">提交订单</a>#}
					</dl>
				</div>
				<h3 class="common_title2">修改密码</h3>
				<div class="site_con">
					<form action="" method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>旧密码：</label>
							<input type="password" name="upassword" value="" id="upassword">
                            <span class="error_tip"></span>
						</div>
                        <div class="form_group">
                            <label>新密码：</label>
                            <input type="password" name="upassword1" value="" id="upassword1">
                            <span class="error_tip"></span>
                        </div>
                        <div class="form_group">
                            <label>确认密码：</label>
                            <input type="password" name="upassword2" value="" id="upassword2">
                            <span class="error_tip"></span>
                        </div>
						<input onclick="fun1()" name="" value="修改密码" class="info_submit">
					</form>
				</div>
		</div>
	</div>

    <script>
    $(function(){

	var error_name = false;
	var error_password = false;
	var error_check_password = false;
	var error_email = false;
	var error_check = false;
	$('#upassword').blur(function() {
		check_pwd();

	});
	$('#upassword1').blur(function() {
		check_pwd2();
	});
	$('#upassword2').blur(function() {
		check_cpwd();
	});
	});
    function fun1() {
        var password1=$('#upassword').val();
        var password2=$('#upassword1').val();
        var password3=$('#upassword2').val();
        $.ajax(
            {
                "url":"/user/password_jiu",
                "type":"get",
                "dataType":"json",
                "data":{
                    password1: password1,
                    password2: password2,
                    password3: password3,
                },
                success:function (data) {
                    if (data.count == 1){
                        alert("密码修改成功,请重新登录")
                        var href=document.getElementById("tuichu").href;window.open(href);
                    }else{
                        alert("你的旧密码输入错误")
                    }
                }
            }
        )
    }
    function check_pwd(){
		var len = $('#upassword').val().length;
		if(len<4||len>20)
		{
			$('#upassword').next().html('密码最少4位，最长20位');
			$('#upassword').next().show();
			error_password = true;
		}
		else
		{
			$('#upassword').next().hide();
			error_password = false;
		}
	}
	function check_pwd2(){
		var len = $('#upassword1').val().length;
		if(len<4||len>20)
		{
			$('#upassword1').next().html('密码最少4位，最长20位');
			$('#upassword1').next().show();
			error_password = true;
		}
		else
		{
			$('#upassword1').next().hide();
			error_password = false;
		}
	}


	function check_cpwd(){
		var pass = $('#upassword1').val();
		var cpass = $('#upassword2').val();
		if(pass!=cpass)
		{
			$('#upassword2').next().html('两次输入的密码不一致');
			$('#upassword2').next().show();
			error_check_password = true;
		}
		else
		{
			$('#upassword2').next().hide();
			error_check_password = false;
		}

	}

    </script>
{% endblock center_body %}